### ISSUE TITLE
ngrok not working with hiddeneye.

### ISSUE THREAD

**Issue by mpandey67** [DarkSecDevelopers/HiddenEye#829] opened 2020-09-17 08:55 UTC
i successfully installed hiddeneye whenever i select any option and step ahead and in the last option i need to use _**ngrok**_ but it does not work and throws me this error ::::-------->>>
I AM USING KALI 2020 ON MAIN MACHINE. 

Traceback (most recent call last):
  File "HiddenEye.py", line 45, in <module>
    server_runner.server_selection(port)
  File "/root/opt/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 64, in server_selection
    NgrokController().establish_connection(port=port)
  File "/root/opt/HiddenEye/controllers/ngrok_controller.py", line 32, in establish_connection
    self._model.connect(port=port, name='HiddenEye Connection', pyngrok_config=self._config_path)
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 178, in connect
    api_url = get_ngrok_process(pyngrok_config).api_url
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 128, in get_ngrok_process
    ensure_ngrok_installed(pyngrok_config.ngrok_path)
AttributeError: 'str' object has no attribute 'ngrok_path'

please help!!!!

**Comment by theCYBERbro** [comment] 2020-09-27 13:05
> i successfully installed hiddeneye whenever i select any option and step ahead and in the last option i need to use _**ngrok**_ but it does not work and throws me this error ::::-------->>>
> I AM USING KALI 2020 ON MAIN MACHINE.
> 
> Traceback (most recent call last):
> File "HiddenEye.py", line 45, in
> server_runner.server_selection(port)
> File "/root/opt/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 64, in server_selection
> NgrokController().establish_connection(port=port)
> File "/root/opt/HiddenEye/controllers/ngrok_controller.py", line 32, in establish_connection
> self._model.connect(port=port, name='HiddenEye Connection', pyngrok_config=self._config_path)
> File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 178, in connect
> api_url = get_ngrok_process(pyngrok_config).api_url
> File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 128, in get_ngrok_process
> ensure_ngrok_installed(pyngrok_config.ngrok_path)
> AttributeError: 'str' object has no attribute 'ngrok_path'
> 
> please help!!!!

I have the same issue on my brand new Ubuntu 20.04.1 LTS

**Comment by sTiKyt** [comment] 2020-09-27 17:08
Duplicate of #821

**Closed by sTiKyt** 2020-09-27 17:08 UTC
Labels: bug
