### ISSUE TITLE
Not working anywhere

### ISSUE THREAD

**Issue by thinker010** [DarkSecDevelopers/HiddenEye#808] opened 2020-09-07 15:23 UTC
Says it's 
![Screenshot_20200907-205306](https://user-images.githubusercontent.com/64064487/92401860-32c80800-f14c-11ea-836b-282a94a14aaf.jpeg)
disconnected from internet pls help. I tried ubuntu, termux ,kali termux ......same problem

**Comment by rebl0x3r** [comment] 2020-09-07 18:19
Well i found a fix for this. 

```
cd HiddenEye/Defs/ActionManager

sed -i 's/dark-sec-official.com/google.com/g' simple_informant.py
```

The problem is, defined is connection with his website, his website is down.
You just replace his website with google and then it's fixed :+1:  

Line 246:
def verify_connection(host='https://google.com'):

**Comment by thinker010** [comment] 2020-09-07 18:24
Hi
Tnx for the reply but .... There is another problem.there is no
actionmanager

**Comment by thinker010** [comment] 2020-09-07 18:40
Hi
Sorry I checked in termux but it's there in ubuntu.....tnx but wat bout
termux?

**Comment by thinker010** [comment] 2020-09-07 18:43
How to replace his website to google

**Comment by darkmidus** [comment] 2020-09-08 04:19
Update to the newest version and tell me if the problem persist

**Comment by thinker010** [comment] 2020-09-08 04:49
Hi
Yes the problem still persists(same problem) I actually tried in termux
.....will it be same or do I need to try in ubuntu or.....?

**Comment by thinker010** [comment] 2020-09-08 14:09
Hi
I tried on rasbian n it doesn't work.

**Comment by sTiKyt** [comment] 2020-09-11 12:11
Duplicate of #773

**Closed by sTiKyt** 2020-09-11 12:11 UTC
Labels: question
