### ISSUE TITLE
[BUG] Serveo doesn't work on termux

### ISSUE THREAD

**Issue by mieucun123** [DarkSecDevelopers/HiddenEye#641] opened 2020-05-31 02:31 UTC
Server don't show any link

**Comment by TheoSanto** [comment] 2020-06-01 11:02
> Server don't show any link

i have the same problem, serveo doesn't generate any URL (both custom and random)

**Comment by sTiKyt** [comment] 2020-06-03 08:38
Give us more info
Help us help you

**Comment by sTiKyt** [comment] 2020-06-03 08:41
Closing here, duplicate of #633 

Please continue discussion in #633

**Closed by sTiKyt** 2020-06-03 08:41 UTC
Labels: not enough information, not-confirmed
