### ISSUE TITLE
Please verify your internet connection.

### ISSUE THREAD

**Issue by Lucifer472** [DarkSecDevelopers/HiddenEye#809] opened 2020-09-08 14:15 UTC
I am using the latest version of hidden eye. I have met every requirements. But still I am getting this error please verify your internet connection. I tried using several vpn but it is not working. I am using termunx apk on android 10 with patch of August.
![Screenshot_20200908-194700](https://user-images.githubusercontent.com/70633757/92488380-19869080-f20c-11ea-9e44-eff5d62f6192.png)

**Comment by luscff99** [comment] 2020-09-09 05:25
I requested a file change to change and remove the error

**Comment by tejaswankalluri82522** [comment] 2020-09-10 06:23
goto: Defs/ActionManaager/simple_informant.py , change line to:
def verify_connection(host='https://google.com'): # Connection check

**Comment by luscff99** [comment] 2020-09-10 06:38
I'm using setoolkit and the following error came up "[*] Error. Unable to clone this specific site. Check your internet connection."
Can someone help me??![Screenshot_20200910-032113.png](https://user-images.githubusercontent.com/70997343/92690271-13310b00-f317-11ea-8497-16bbdb7a5362.png)

**Comment by ziadBn** [comment] 2020-09-10 09:28
I have this problem too buddy

**Comment by Lucifer472** [comment] 2020-09-10 09:40
Can you describe that procces in more details like how to go actually change the data like how to find the file. Because I can't find the specific path in file manger.

**Comment by Samurai9954** [comment] 2020-09-10 09:49
This Error is being caused as the script they have written to check for internet access is actually sending a get request to there official website which is now down... so to fix this error as @tejaswankalluri82522 said, cd into Defs/ActionManaager/ directory and edit the simple_informant.py kid lines to 
```
def verify_connection(host='https://google.com'):
```
i will close this issue now, but if any issues are left no problem in re opening it 👍 :)

**Comment by tejaswankalluri82522** [comment] 2020-09-10 10:47
> Can you describe that procces in more details like how to go actually change the data like how to find the file. Because I can't find the specific path in file manger.
watch this video : https://www.youtube.com/watch?v=ZTfOSjaTRSM&feature=youtu.be

**Comment by rebl0x3r** [comment] 2020-09-10 13:51
Well i found a fix for this.

```
cd HiddenEye/Defs/ActionManager

sed -i 's/dark-sec-official.com/google.com/g' simple_informant.py
```

The problem is, defined is connection with his website, his website is down.
You just replace his website with google and then it's fixed +1

Line 246:
`def verify_connection(host='https://google.com'):`

**Comment by luscff99** [comment] 2020-09-10 15:38
![Screenshot_20200910-123726.png](https://user-images.githubusercontent.com/70997343/92755748-857b0d00-f362-11ea-9dbc-783cf0b365fe.png)
How to resolve, help me pleaseeeee

**Comment by Samurai9954** [comment] 2020-09-10 16:21
> ![Screenshot_20200910-123726.png](https://user-images.githubusercontent.com/70997343/92755748-857b0d00-f362-11ea-9dbc-783cf0b365fe.png)
> How to resolve, help me pleaseeee

sudo pip3 install requests

**Comment by Lucifer472** [comment] 2020-09-10 16:37
Ok I done what you asked me to do here look


![Screenshot_20200910-220430](https://user-images.githubusercontent.com/70633757/92764244-dfef8a00-f3b1-11ea-81d0-81e0367a7781.png)

But I am still having the same issue here please fix this.....

![Screenshot_20200910-220526](https://user-images.githubusercontent.com/70633757/92764386-03b2d000-f3b2-11ea-8ab6-576ed770fe45.png)

**Comment by Samurai9954** [comment] 2020-09-10 16:48
@Lucifer472 Edit the file with vim, just change the Line 246 to:
```
def verify_connection(host='https://google.com'):
```
This will fix the issue
if you dont know how to use vim, then ¯\_(ツ)_/¯

**Comment by luscff99** [comment] 2020-09-10 16:51
> @Lucifer472 Edit the file with vim, just change the Line 246 to:
> ```
> def verify_connection(host='https://google.com'):
> ```
> This will fix the issue
> if you dont know how to use vim, then ¯\_(ツ)_/¯

![Screenshot_20200910-132935.png](https://user-images.githubusercontent.com/70997343/92766576-b82a0300-f36c-11ea-9615-9dad1ebd8820.png)how to resolve bro?

**Comment by Samurai9954** [comment] 2020-09-10 16:53
I think you messed up something, wait i will fork this repo and edit and give the link in 2 minutes :)

**Comment by Samurai9954** [comment] 2020-09-10 16:56
Okay now clone this repo - https://github.com/Samurai9954/HiddenEye.git
after doing it try again :D

**Comment by luscff99** [comment] 2020-09-10 16:56
> I think you messed up something, wait i will fork this repo and edit and give the link in 2 minutes :)

Ok

**Comment by luscff99** [comment] 2020-09-10 16:57
> Okay now clone this repo - https://github.com/Samurai9954/HiddenEye.git
> after doing it try again :D

Ok ok

**Comment by Samurai9954** [comment] 2020-09-10 16:58
If getting any new errors, ask here :D i have experience in python and tunneling through ngrok and serveo so i will be here :)

**Comment by luscff99** [comment] 2020-09-10 16:59
> If getting any new errors, ask here :D i have experience in python and tunneling through ngrok and serveo so i will be here :)

![Screenshot_20200910-135814.png](https://user-images.githubusercontent.com/70997343/92767780-d17f7f00-f36d-11ea-97f2-12199ec89626.png)

**Comment by Samurai9954** [comment] 2020-09-10 17:00
Ok, delete the already there hiddeneye with the command
```
rm -r HiddenEye
```
then try to clone it

**Comment by luscff99** [comment] 2020-09-10 17:02
> Ok, delete the already there hiddeneye with the command
> ```
> rm -r HiddenEye
> ```
> then try to clone it 

I'm cloning, as soon as I finish I'll be back here

**Comment by Samurai9954** [comment] 2020-09-10 17:08
you done yet? its been 7 minutes XD

**Comment by luscff99** [comment] 2020-09-10 17:18
> you done yet? its been 7 minutes XD

![Screenshot_20200910-141647.png](https://user-images.githubusercontent.com/70997343/92770511-64b9b400-f370-11ea-88da-cef0b6f74bc6.png)
Thank you bro, I love u haha

**Comment by luscff99** [comment] 2020-09-10 17:34
> you done yet? its been 7 minutes XD

![Screenshot_20200910-143237.png](https://user-images.githubusercontent.com/70997343/92773032-9cc1f680-f372-11ea-8241-915cb8781fcc.png)

When I try to connect for the second time this appears:
![IMG-20200910-WA0020.jpg](https://user-images.githubusercontent.com/70997343/92773150-bf540f80-f372-11ea-8962-a59011fc0005.jpg)

**Comment by luscff99** [comment] 2020-09-10 17:44
![Screenshot_20200910-144035.png](https://user-images.githubusercontent.com/70997343/92774671-16a6af80-f374-11ea-8790-c39da7d2067c.png)

This problem happens when I try to use the "serveo"

**Comment by Samurai9954** [comment] 2020-09-11 03:25
I also had these issues too, to fix them don't do them straight from hiddeneye, choose localhost in hiddeneye, then do start ngrok or serveo in another terminal i repeat not straight from the hiddeneye program... i did the same thing :D

**Comment by luscff99** [comment] 2020-09-11 03:29
> I also had these issues too, to fix them don't do them straight from hiddeneye, choose localhost in hiddeneye, then do start ngrok or serveo in another terminal i repeat not straight from the hiddeneye program... i did the same thing :D

but localhost does not open on external connections

**Comment by Samurai9954** [comment] 2020-09-11 04:02
thats what i said, do it on localhost and then start ngrok or serveo externally through a different terminal in termux

**Comment by luscff99** [comment] 2020-09-11 06:15
> thats what i said, do it on localhost and then start ngrok or serveo externally through a different terminal in termux 

as soon as you said i tried and got it, thanks so much for your patience.

**Comment by luscff99** [comment] 2020-09-11 06:32
> thats what i said, do it on localhost and then start ngrok or serveo externally through a different terminal in termux 

My serveo ![Screenshot_20200911-033115.png](https://user-images.githubusercontent.com/70997343/92875378-5a82ce80-f3df-11ea-82e9-e91f16beca1e.png)doesn't work

**Comment by Samurai9954** [comment] 2020-09-11 08:18
dude, when starting the hiddeneye on localhost select the port 8080 and then try to run that command again, if doesn't work start it on port 30 then try

**Comment by sTiKyt** [comment] 2020-09-11 12:09
Duplicate of #773 , closing here

**Closed by sTiKyt** 2020-09-11 12:09 UTC
Labels: not-confirmed, question
