### ISSUE TITLE
internet connection

### ISSUE THREAD

**Issue by eronic06** [DarkSecDevelopers/HiddenEye#795] opened 2020-08-29 14:53 UTC
it say that i have internet connection problem ???

**Comment by SANISH-sanish** [comment] 2020-08-29 15:21
it always says u are not connected to internet but when i ping google.com it pings and all the websites are opening

**Comment by zeyad1706** [comment] 2020-08-30 11:04
> it always says u are not connected to internet but when i ping google.com it pings and all the websites are opening

**Comment by darkmidus** [comment] 2020-08-30 15:06
I'll take a look at this issue tonight and fix it.

**Comment by bond0707** [comment] 2020-08-30 16:45
Duplicate of #773

**Comment by bond0707** [comment] 2020-08-30 16:46
There is a solution by another user on #773

**Comment by sTiKyt** [comment] 2020-09-27 17:10
This issue is open but wasn't active for 30 days now, and was fixed after latest dev branch merge, closing here

**Closed by sTiKyt** 2020-09-27 17:10 UTC
