### ISSUE TITLE
Related to hiddeneye it is showing that internet disconnected but my net is working properly can anybody from the developer side help me in this matter ?[BUG]

### ISSUE THREAD

**Issue by himanshumehla** [DarkSecDevelopers/HiddenEye#792] opened 2020-08-28 01:07 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - Python [e.g. 3.6.1]
 - HiddenEye Version [e.g. 1.0.22]

**Additional context**

**Comment by sTiKyt** [comment] 2020-08-28 17:18
Duplicate of #773

**Closed by sTiKyt** 2020-08-28 17:18 UTC
Labels: bug, not-confirmed
