### ISSUE TITLE
[BUG] Ngrok is not working.

### ISSUE THREAD

**Issue by Lucifer472** [DarkSecDevelopers/HiddenEye#830] opened 2020-09-17 10:38 UTC
Hey!! I am using Userland apk with debian system because I had this same issue in termunx. 

When I try to use Ngrok server it gives me this error

![Screenshot_20200917-160351](https://user-images.githubusercontent.com/70633757/93459752-d6a97480-f8ff-11ea-95a9-a9f1ffbd88d1.png)

I am using Nokia 3.2
With Android 10.

Everything else is up to date.

**Comment by keniobats** [comment] 2020-09-18 19:07
Hello,

Same issue here, with current version of HiddenEye, running on kali linux rolling edition.

**Comment by Mushinako** [comment] 2020-09-20 05:30
The issue seems to be [here](https://github.com/DarkSecDevelopers/HiddenEye/blob/master/controllers/ngrok_controller.py#L32).
```py
self._model.connect(port=port, name='HiddenEye Connection', pyngrok_config=self._config_path)
```
Here the config path (str) is passed into `ngrok.connect` as `pyngrok_config`, but the function [expects an object here](https://github.com/alexdlaird/pyngrok/tree/master/pyngrok#L156).

**Comment by sTiKyt** [comment] 2020-09-27 17:08
Duplicate of #821

**Closed by sTiKyt** 2020-09-27 17:08 UTC
Labels: bug, not-confirmed
