### ISSUE TITLE
[BUG][!] Network error. Please verify your internet connection.

### ISSUE THREAD

**Issue by vqvqo** [DarkSecDevelopers/HiddenEye#804] opened 2020-09-02 23:04 UTC
There are a problem , [!] Network error. Please verify your internet connection.
Can you help us ?

**Comment by trolluu** [comment] 2020-09-03 19:05
https://youtu.be/ZTfOSjaTRSM

**Comment by jeffjbowie** [comment] 2020-09-04 15:32
210:Defs/ActionManaager/simple_informant.py , changed line to:
`def verify_connection(host='https://google.com'):  # Connection check`

**Comment by darkmidus** [comment] 2020-09-04 19:21
Please update HiddenEye to the newest version

**Comment by Morsmalleo** [comment] 2020-09-05 03:08
Just installed HiddenEye and its doing the same thing for me on Kali Linux 2020.3

**Comment by ninjaspl0it** [comment] 2020-09-05 08:34
Can confirm same issue here

**Comment by ivelinvitanov** [comment] 2020-09-05 09:39
Hello, im kinda new in Linux and im having the same problem. Google is 100% active in my country !

**Comment by johndoehack** [comment] 2020-09-05 17:04
do this pip3 install -r requirements.txt then pip install -r requirements.txt
hiddeneye still runs on python2.7 that should fix the problem

**Comment by kaianinja** [comment] 2020-09-06 18:05
> 210:Defs/ActionManaager/simple_informant.py , change line to:
> `def verify_connection(host='https://google.com'):  # Connection check`
> 
> looks to be a simple KillSwitch.

When i try to edit this is what comes up i dont know if i am doing something wrong but this is root edit. I went to defs actionmanager and typed nano simple_informant.py
[![20200906_140355.jpg](https://user-images.githubusercontent.com/70761047/92332199-d67cbf80-f049-11ea-80a5-06f4394fe942.jpg)

**Comment by darkmidus** [comment] 2020-09-06 18:09
@kaianinja I have already said st the top to update your HiddenEye and the issue will be resolved. We fixed it many updates ago.

**Comment by Morsmalleo** [comment] 2020-09-07 00:29
Its got nothing to do with updating HiddenEye I updated hidden eye many times and nothing, I had to follow the YouTube link above yo fix the problem so problem is solved for me

**Comment by darkmidus** [comment] 2020-09-08 04:08
@Morsmalleo This is a mistake on my part. I forgot to accept the pull request so the update was never pushed. The update fixing the network error should be out.

**Comment by sTiKyt** [comment] 2020-09-11 12:08
Duplicate of #773 , learn to search before asking... Closing here.

**Closed by sTiKyt** 2020-09-11 12:08 UTC
Labels: bug, not-confirmed
