### ISSUE TITLE
[BUG] i suppose its ngrok or something

### ISSUE THREAD

**Issue by pwned-cpp** [DarkSecDevelopers/HiddenEye#836] opened 2020-09-24 00:30 UTC
**Describe the bug**

**To Reproduce**
1. Go to '08'
2. Click on 'enter', port: 1024

**Expected behavior**

**Screenshots**

https://user-images.githubusercontent.com/63930068/94086988-0f63b500-fdfc-11ea-80ab-bfa89e2dfeeb.png

**Device (please complete the following information):**
 - OS: [Parrot OS]
 - Python [3.8.5]
 - HiddenEye Version [1.0.0]

**Additional context**

it happens everytime, i ran pip3 and it said all the requirements were already installed.

**Comment by sTiKyt** [comment] 2020-09-27 17:09
Duplicate of #821

**Closed by sTiKyt** 2020-09-27 17:09 UTC
Labels: bug, not-confirmed
