### ISSUE TITLE
Ngrok Is not Working!!!!

### ISSUE THREAD

**Issue by DarkSyntax7** [DarkSecDevelopers/HiddenEye#826] opened 2020-09-16 08:50 UTC
![2020-09-16_14-13](https://user-images.githubusercontent.com/66020029/93314648-af7f7400-f827-11ea-9a06-5b3d60645fcc.png)

Please do something !!

**Comment by sTiKyt** [comment] 2020-09-27 17:08
Duplicate of #821

**Closed by sTiKyt** 2020-09-27 17:08 UTC
Labels: bug
