### ISSUE TITLE
[BUG] Mind Blowing... 

### ISSUE THREAD

**Issue by AminViewer** [DarkSecDevelopers/HiddenEye#824] opened 2020-09-14 19:45 UTC
**Please Help...**![Screenshot_20200914_214412.jpg](https://user-images.githubusercontent.com/71229552/93130944-9c5b8f80-f6d3-11ea-912e-15be0f6ef68d.jpg)

**Comment by sTiKyt** [comment] 2020-09-27 17:07
Duplicate of #821

**Closed by sTiKyt** 2020-09-27 17:07 UTC
Labels: bug, not-confirmed
