### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by WickedG0d** [DarkSecDevelopers/HiddenEye#486] opened 2020-01-06 15:01 UTC
Traceback (most recent call last):
  File "HiddenEye.py", line 50, in <module>
    getCredentials(port)
  File "/root/Tools/HiddenEye/Defs/Actions.py", line 916, in getCredentials
    ip = re.search("Victim Public IP: (\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})[\n,\r]", lines).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

Here's the error i am getting

**Comment by An0nUD4Y** [comment] 2020-01-07 03:09
@WickedG0d  We are Aware of This Issue..
Will Solve it As Soon As Possible..

**Comment by gjhami** [comment] 2020-01-08 05:42
I'd like to close this issue as it appears to be a duplicate of #469

**Closed** 2020-01-20 08:27 UTC
Labels: help wanted
