### ISSUE TITLE
Can't use Serveo with slow connection

### ISSUE THREAD

**Issue by sTiKyt** [DarkSecDevelopers/HiddenEye#125] opened 2018-10-28 20:37 UTC
After reorganization i can't fix Serveo error, that why i started dev branch:
`Traceback (most recent call last):
  File "HiddenEye.py", line 38, in <module>
    selectServer()
  File "/home/stikyt/Documents/GitHub/HiddenEye/Defs/Actions.py", line 78, in selectServer
    runServeo()
  File "/home/stikyt/Documents/GitHub/HiddenEye/Defs/Actions.py", line 100, in runServeo
    output = check_output("grep -o 'https://[0-9a-z]*\.serveo.net' link.url", shell=True)
  File "/usr/lib/python3.7/subprocess.py", line 389, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 481, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'grep -o 'https://[0-9a-z]*\.serveo.net' link.url' returned non-zero exit status 1.
`

**Comment by sTiKyt** [comment] 2018-10-28 20:43
Sorry for this bug but i can't understand waht am i doing wrong.

**Comment by usama7628674** [comment] 2018-10-29 02:05
@sTiKyt Run it again.

**Comment by sTiKyt** [comment] 2018-10-29 21:35
Im sure that i'm downloaded your fix but this seems like this:
![image](https://user-images.githubusercontent.com/35602029/47681843-3e069000-dbd3-11e8-8f52-c181c0af2c1b.png)

**Comment by sTiKyt** [comment] 2018-10-29 21:35
@usama7628674

**Comment by sTiKyt** [comment] 2018-10-29 21:40
And please don't close issues before this get approved @An0nUD4Y

**Comment by usama7628674** [comment] 2018-10-30 01:00
I'll check dev branch

**Comment by sTiKyt** [comment] 2018-10-30 01:01
@usama7628674 nice

**Comment by usama7628674** [comment] 2018-10-30 01:02
And merge it in master branch

**Comment by sTiKyt** [comment] 2018-10-30 01:03
@usama7628674 I'll merge after bug fix, and always work with dev branch. Master branch must be stable.

**Comment by usama7628674** [comment] 2018-10-30 01:06
The problem is if you're having latency or internet timeout issue then you get that error above in screenshot.

**Comment by usama7628674** [comment] 2018-10-30 11:48
@sTiKyt fixed

**Comment by usama7628674** [comment] 2018-10-30 14:44
@sTiKyt Yes it does if your internet is not stable

**Comment by sTiKyt** [comment] 2018-10-30 14:48
> @sTiKyt Yes it does if your internet is not stable

That was working earlier, so, now people can't use it if have 1Mbyte/sec?

**Comment by sTiKyt** [comment] 2018-11-15 18:02
This was working, please fix it

**Comment by usama7628674** [comment] 2018-11-16 03:48
@sTiKyt Please do `git pull` and give me output of `git log`.You should be on latest commit.This was fixed earlier.

**Comment by sTiKyt** [comment] 2018-12-06 23:16
@usama7628674 that 2.2.0 release 
![image](https://user-images.githubusercontent.com/35602029/49617530-a2302700-f9bd-11e8-9675-c82422c67632.png)

**Comment by usama7628674** [comment] 2018-12-07 04:02
@sTiKyt Fixed in latest commit will print `Network error` if serveo link does not generate in time.

**Closed** 2018-12-09 11:40 UTC
Labels: bug
