### ISSUE TITLE
[BUG] Ngrok working but weird error ?!

### ISSUE THREAD

**Issue by KatzeMau** [DarkSecDevelopers/HiddenEye#833] opened 2020-09-20 10:13 UTC
t=2020-09-20T12:10:56+0200 lvl=warn msg="failed to check for update" obj=updater err="Post https://update.equinox.io/check: context deadline exceeded"

t=2020-09-20T12:11:02+0200 lvl=eror msg="failed to reconnect session" obj=csess id=3314a4748efd err="dial tcp [2600:1f16:d83:1201::6e74:1]:443: i/o timeout"

Can't find any latest connections.
Traceback (most recent call last):
  File "HiddenEye.py", line 45, in <module>
    server_runner.server_selection(port)
  File "/Users/tim/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 64, in server_selection
    NgrokController().establish_connection(port=port)
  File "/Users/tim/HiddenEye/controllers/ngrok_controller.py", line 32, in establish_connection
    self._model.connect(port=port, name='HiddenEye Connection', pyngrok_config=self._config_path)
  File "/usr/local/lib/python3.8/site-packages/pyngrok/ngrok.py", line 176, in connect
    api_url = get_ngrok_process(pyngrok_config).api_url
  File "/usr/local/lib/python3.8/site-packages/pyngrok/ngrok.py", line 126, in get_ngrok_process
    ensure_ngrok_installed(pyngrok_config.ngrok_path)
AttributeError: 'str' object has no attribute 'ngrok_path'

**Device (please complete the following information):**
 - OS: MAC OS NEWEST
 - Python 3
 - HiddenEye Version NEWEST

**Comment by sTiKyt** [comment] 2020-09-27 17:09
Duplicate of #821

**Closed by sTiKyt** 2020-09-27 17:09 UTC
Labels: bug, not-confirmed
