### ISSUE TITLE
[BUG]NGROK ERROR

### ISSUE THREAD

**Issue by Saami10** [DarkSecDevelopers/HiddenEye#835] opened 2020-09-21 14:36 UTC
Traceback (most recent call last):
  File "HiddenEye.py", line 45, in <module>
    server_runner.server_selection(port)
  File "/root/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 64, in server_selection
    NgrokController().establish_connection(port=port)
  File "/root/HiddenEye/controllers/ngrok_controller.py", line 32, in establish_connection
    self._model.connect(port=port, name='HiddenEye Connection', pyngrok_config=self._config_path)
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 176, in connect
    api_url = get_ngrok_process(pyngrok_config).api_url
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 126, in get_ngrok_process
    ensure_ngrok_installed(pyngrok_config.ngrok_path)
AttributeError: 'str' object has no attribute 'ngrok_path'

GETTING THIS ERROR WHILE STARTING NGROK

**Comment by sTiKyt** [comment] 2020-09-21 16:57
@Saami10 Was fixed in Dev branch

**Comment by vanss-x** [comment] 2020-09-27 10:00
please tell how to fix it 
it giving me ngrok error and i cant send it out of the internet

**Comment by sTiKyt** [comment] 2020-09-27 12:33
@vanss-x Learn to read old issues before you create new ones..

**Comment by sTiKyt** [comment] 2020-09-27 17:09
Duplicate of #821

**Closed by sTiKyt** 2020-09-27 17:09 UTC
Labels: bug, not-confirmed

**Comment by vanss-x** [comment] 2020-09-27 17:15
Please fix the script the ngrok server doesn't work in new version

**Comment by sTiKyt** [comment] 2020-09-27 17:18
@vanss-x i told you to go to #821, this issues is closed and i'm locking conversation due to it.
