### ISSUE TITLE
Ngrok doesnt connect with HiddenEye

### ISSUE THREAD

**Issue by waffler12** [DarkSecDevelopers/HiddenEye#825] opened 2020-09-14 21:35 UTC
I dont know if it just me or maybe im just stupid as im new but when i load up hiddeneye using "python3 HiddenEye.py" this comes up 

Traceback (most recent call last):                                         
  File "HiddenEye.py", line 45, in <module>                                
    server_runner.server_selection(port)                                   
  File "/home/cjlt22/Desktop/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 64, in server_selection                                      
    NgrokController().establish_connection(port=port)                      
  File "/home/cjlt22/Desktop/HiddenEye/controllers/ngrok_controller.py", line 32, in establish_connection                                             
    self._model.connect(port=port, name='HiddenEye Connection', pyngrok_config=self._config_path)                                                     
  File "/home/cjlt22/.local/lib/python3.8/site-packages/pyngrok/ngrok.py", line 176, in connect                                                       
    api_url = get_ngrok_process(pyngrok_config).api_url                    
  File "/home/cjlt22/.local/lib/python3.8/site-packages/pyngrok/ngrok.py", line 126, in get_ngrok_process                                             
    ensure_ngrok_installed(pyngrok_config.ngrok_path)                      
AttributeError: 'str' object has no attribute 'ngrok_path' 

im on kali linux and python 3.8.5, if anyone can help me please or refer me to a way of doing phishing out side my local network

**Comment by sTiKyt** [comment] 2020-09-27 17:07
Duplicate of #821

**Closed by sTiKyt** 2020-09-27 17:07 UTC
Labels: bug, not-confirmed
